module.exports.Token = require('./token.model');
module.exports.User = require('./user.model');
module.exports.Service = require('./service.model')
module.exports.Location=require('./location.model')
module.exports.Setting=require('./setting.model')
module.exports.Notification=require('./notifaction.model')
module.exports.SponserTournament=require('./sponserTournament.model')
module.exports.LookingToPlay=require('./lookingToPlay.model')
module.exports.TeeSheet=require('./teeSheet.model')